parameters:
  - name: 'dbName'
    type: string
  - name: 'dbHost'
    type: string
  - name: 'dbPsw'
    type: string
  - name: 'dbUsername'
    type: string

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        chmod +x run.sh
        ./run.sh $DB
    env:
      DB: ${{ parameters.dbName }}
      PGHOST: ${{ parameters.dbHost }}
      PGPORT: 5432
      PGUSERNAME: ${{ parameters.dbUsername }}
      PGPASSWORD: ${{ parameters.dbPsw }}
    displayName: "Applying migration on ${{ parameters.dbName }} database"
