pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: Env
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - uat
      - prod
  - name: dbs
    type: object
    default:
      - citizen
      - payhub
      - analytics

variables:
  ${{ if eq(parameters.Env, 'dev') }}:
    AZURE_SERVICE_CONNECTION: '$(dev_azure_sub_serv_conn)'
    ENV_SHORT: 'd'

  ${{ if eq(parameters.Env, 'uat') }}:
    AZURE_SERVICE_CONNECTION: '$(uat_azure_sub_serv_conn)'
    ENV_SHORT: 'u'

  ${{ if eq(parameters.Env, 'prod') }}:
    AZURE_SERVICE_CONNECTION: '$(prod_azure_sub_serv_conn)'
    ENV_SHORT: 'p'

  poolImage: 'p4pa-${{ parameters.Env }}-linux-app'
  KEY_VAULT_NAME: 'p4pa-${{ variables.ENV_SHORT }}-payhub-kv'

stages:
  - stage: initialization_jobs
    displayName: "Init ${{ parameters.Env }}"
    jobs:
      - job: initialization
        pool: $(poolImage)
        displayName: "Applying DB schema migration on ${{ parameters.Env }}"
        steps:
          - checkout: self

          - task: AzureKeyVault@2
            displayName: "Get secrets"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              keyVaultName: $(KEY_VAULT_NAME)
              secretsFilter: 'db-mypay-login-username,db-mypay-login-password,db-host,db-piattaforma-unitaria-login-username,db-piattaforma-unitaria-login-password,db-analytics-login-username,db-analytics-login-password'

          - ${{ each db in parameters.dbs }}:
            - task: Bash@3
              displayName: "Set ${{ db }} db configuration"
              inputs:
                targetType: 'inline'
                script: |
                  if [ ${{db}} = "payhub" ];
                  then
                    echo "##vso[task.setvariable variable=DB_USERNAME;issecret=true]$(db-piattaforma-unitaria-login-username)"
                    echo "##vso[task.setvariable variable=DB_PASSWORD;issecret=true]$(db-piattaforma-unitaria-login-password)"
                  elif [ ${{db}} = "analytics" ];
                  then
                    echo "##vso[task.setvariable variable=DB_USERNAME;issecret=true]$(db-analytics-login-username)"
                    echo "##vso[task.setvariable variable=DB_PASSWORD;issecret=true]$(db-analytics-login-password)"
                  else
                    echo "##vso[task.setvariable variable=DB_USERNAME;issecret=true]$(db-mypay-login-username)"
                    echo "##vso[task.setvariable variable=DB_PASSWORD;issecret=true]$(db-mypay-login-password)"
                  fi
            - template: templates\db-update.yml
              parameters:
                dbName: ${{ db }}
                dbHost: $(db-host)
                dbPsw: $(DB_PASSWORD)
                dbUsername: $(DB_USERNAME)
